// <auto-generated />
using System;
using LiarisHR.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LiarisHR.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("LiarisHR.API.Models.Business", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Business");
                });

            modelBuilder.Entity("LiarisHR.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BusinessNameId");

                    b.Property<string>("City");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<DateTime>("HireDate");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<int>("PayRate");

                    b.Property<string>("ProfileImageURL");

                    b.Property<string>("Skills");

                    b.Property<string>("State");

                    b.Property<int>("VacationHours");

                    b.HasKey("Id");

                    b.HasIndex("BusinessNameId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LiarisHR.API.Models.User", b =>
                {
                    b.HasOne("LiarisHR.API.Models.Business", "BusinessName")
                        .WithMany("User")
                        .HasForeignKey("BusinessNameId");
                });
#pragma warning restore 612, 618
        }
    }
}
